### ISSUE TITLE
Support long comments in the header of `style.css` files

### ISSUE THREAD

**Issue by ntwb** [WordPress-Coding-Standards/stylelint-config-wordpress#150]
Given a typical theme header such as this below stylelint should include exceptions for long lines within these comments, typically URLs, Description, and Tags lines are longer than 80 characters:

```css
/*
Theme Name: Twenty Ten
Theme URI: https://wordpress.org/themes/twentyten/themes/twentyten/themes/twentyten/themes/twentyten/
Description: The 2010 theme for WordPress is stylish, customizable, simple, and readable -- make it yours with a custom menu, header image, and background. Twenty Ten supports six widgetized areas (two in the sidebar, four in the footer) and featured images (thumbnails for gallery posts and custom header images for posts and pages). It includes stylesheets for print and the admin Visual Editor, special styles for posts in the "Asides" and "Gallery" categories, and has an optional one-column page template that removes the sidebar.
Author: the WordPress team
Author URI: https://wordpress.org/
Version: 2.3
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Tags: blog, two-columns, custom-header, custom-background, threaded-comments, sticky-post, translation-ready, microformats, rtl-language-support, editor-style, custom-menu, flexible-header, featured-images, footer-widgets, featured-image-header
Text Domain: twentyten
*/

a {
	top: 0.2em;
}

...
```
