### ISSUE TITLE
Is the regex in the 'selector-class-pattern' and 'selector-id-pattern' rules missing something?

### ISSUE THREAD

**Issue by sandrab** [WordPress-Coding-Standards/stylelint-config-wordpress#236]
When I run the stylelint, it accepts camelCase selectors, like:
```
.myDiv {
    color: #fff;
}
#commentForm {
    color: #fff;
}
```
I would expect these to be caught by the 'selector-class-pattern' and 'selector-id-pattern' rules because the [WordPress CSS Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#selectors) state to avoid camelCase. But these rules use a regex like this:

`'^[a-z]+(-[a-z]+)*'`

Could it be the regex in these rules is missing and end indicator? So, should they not end with: `$` to avoid any characters after the pattern?

`'^[a-z]+(-[a-z]+)*$'`

Compare with the examples in the [stylelint faq](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/faq.md#how-do-i-configure-the--pattern-rules-for-common-css-naming-conventions-like-kebab-case) that have the `$` at the end as well.

Or is this the desired behaviour? In that case I am obviously missing something.

**Comment by ntwb** [comment]
Sincere apologies @sandrab for not replying before now!

And you are correct, it looks like the regex indeed requires updating.

It looks also like the stylelint docs could do with an update too as the `^([a-z][a-z0-9]*)(-[a-z0-9]+)*$` regex throws warnings for these selector styles and it should not:

```css
h1,
.heading-size-1 {
	font-size: 3.6rem;
	font-weight: 800;
	line-height: 1.138888889;
}

h2,
.heading-size-2 {
	font-size: 3.2rem;
}

h3,
.heading-size-3 {
	font-size: 2.8rem;
}
```
