### ISSUE TITLE
Update `declaration-colon-newline-after` rule

### ISSUE THREAD

**Issue by ntwb** [WordPress-Coding-Standards/stylelint-config-wordpress#59]
> https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#values
> 
> > _"Multiple comma-separated values for one property should be separated by either a space or a newline, including within rgba(). Newlines should be used for lengthier multi-part values such as those for shorthand properties like box-shadow and text-shadow. Each subsequent value after the first should then be on a new line, indented to the same level as the selector and then spaced over to left-align with the previous value."_

Current rule: `"declaration-colon-newline-after": "always-multi-line",`

Correct:

``` css
.class {
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.5),
                 0 1px 0 #fff;
}
```

Incorrect:

``` css
.class {
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.5),
        0 1px 0 #fff;
}

.class {
    text-shadow: 
        0 -1px 0 rgba(0, 0, 0, 0.5),
        0 1px 0 #fff;
}
```
